Capstone Project
developertariq/microverse-capstone-1 pull request #1
Opened 2022-11-24 12:09 UTC by developertariq

## Major implementation 🌹🌹
### ✔Followed these [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)
 ### ✔Built only below pages:
     The home page.
     The about page.
### ✔The home page has a link in the menu to the about page.
### ✔The logo in the header links to the home page.
### ✔The section "Featured speakers" is created dynamically in JavaScript.
### ✔Credit was provided to the original designer [Cindy Shin in Behance](https://www.behance.net/adagio07) and the [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/)
### ♻ [The private recording about the project](https://www.loom.com/share/81793fc6e598441a96ecda04e835fe8c) (Newly recorded)
### ♻ Changes are reflected on published pages

## ✔This project is developed to fulfill the following objectives: 
- Use semantic HTML tags.
- Apply best practices in HTML code.
- Use CSS selectors correctly.
- Use CSS box model.
- Use Flexbox to place elements in the page.
- Demonstrate ability to create UIs adaptable to different screen sizes using media queries.
- Use GitHub Pages to deploy web pages.
- Apply JavaScript best practices and language style guides in code.
- Use JavaScript to manipulate DOM elements.
- Use JavaScript events.
- Use objects to store and access data.
- Communicate technical concepts to other technical people.

2022-11-24 14:24 UTC, jerryowusu requested changes
Hi @developertariq , 

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, I've found some room for improvement that can help you accomplish a more readable/clean code and make your project look professional :sunglasses:

![almost-there-reach](https://user-images.githubusercontent.com/65233860/203807340-69dec51f-872a-440a-bf2c-2e487dad1c85.gif)


## Highlights
All linters are passing :heavy_check_mark: 
Followed GitHub flow :heavy_check_mark: 
Nice code structure :heavy_check_mark: 



## Required Changes ♻️

- [ ] Your video is missing highlight about a piece of code that you find very interesting or is very proud of. Kindly update the project documentation video and add that. :wink: 

- [ ] Kindly ensure that the top dark nav bar contains the logout and language links in addition to the social media links to match the design. 

 Your design            |  The  design 
:-------------------------:|:-------------------------:
![Screenshot from 2022-11-24 13-31-00](https://user-images.githubusercontent.com/65233860/203797126-21868ad7-9d3f-4217-ab10-c4f22c25c5c3.png)  |  ![Screenshot from 2022-11-24 13-35-14](https://user-images.githubusercontent.com/65233860/203797162-b46e3fff-c73f-4a82-a412-c8457ab19531.png)


- [ ] Please note that the desktop version footer of the about page has a dark background instead of the white background you are currently using. Moreover, there is no footer for the mobile version of the  home page. Kindly check and fix these to match the design. :wink: 

- [ ] Kindly ensure that all images have alt attributes and their appropriate values in conformity with best standard practices. :pray: Some of your images do not have empty alt attribute values as shown below 

![Screenshot from 2022-11-24 13-47-43](https://user-images.githubusercontent.com/65233860/203799790-c1c441db-819c-4e16-bbc8-9be896cbdc1e.png)


- [ ] Kindly make sure that your css stylesheet is DRY in order to conform with best practices. I see a lot of repetions. For instance, you have repeated the same code `@media screen and (min-width: 768px) ` 6 times in your main.css file and 3 times in your about.css file

- [ ] Kindly ensure that the pages use the exact same colors for text, backgrounds, borders etc from the original design. I can see you are using `#ef513c` for `#ec5242` and `#272a31` instead of `#d3d3d3` for some of the text and background. Please consider going through your code to correct this anomaly. 

 Your design            |  The  design 
:-------------------------:|:-------------------------:
![Screenshot from 2022-11-24 14-01-50](https://user-images.githubusercontent.com/65233860/203802668-ad2af861-3b5c-44d7-be0d-2ac117f6a7ac.png)  |  ![Screenshot from 2022-11-24 14-01-34](https://user-images.githubusercontent.com/65233860/203802714-f50677d9-f325-4d88-9c2d-3d741f17d421.png)

 Your design            |  The design 
:-------------------------:|:-------------------------:
![Screenshot from 2022-11-24 14-05-29](https://user-images.githubusercontent.com/65233860/203803556-4b38a2bd-39c0-4b57-9624-8be95fb1de04.png)  |  ![Screenshot from 2022-11-24 14-05-35](https://user-images.githubusercontent.com/65233860/203803596-577ac3a3-b8fb-4331-8e70-61a06b61ca0b.png)


- [ ] Kindly ensure that all pages have similar spacing, shadows, and paddings as well as margins as the original design. The margins and paddings of the home and about page is different from the design. Kindly check and fix this. 

 Your design            |  The design 
:-------------------------:|:-------------------------:
![Screenshot from 2022-11-24 14-08-27](https://user-images.githubusercontent.com/65233860/203805415-ca17a175-d2a5-462a-979b-235c4f810ade.png)  |  ![Screenshot from 2022-11-24 14-09-12](https://user-images.githubusercontent.com/65233860/203805444-79f4f155-5a3f-4990-9dfb-6f90afbe6c66.png)




_Check the comments under the review._

## Optional suggestions

- [ ] [OPTIONAL] Hello @developertariq, :wave: Kindly ensure that all your changes for the project are present in the final submission branch. :pray:  Currently it looks like you have merge and deleted some branches before submitting the last one for review which does not make your work look proffessional. It also makes it difficult for reviewers to check and review your code :tired_face: 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-25 05:19 UTC, Olamarx requested changes
Hi @developertariq, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
<img src="https://media3.giphy.com/media/hXz6GN0ZilLwhgLo49/giphy.gif"/>

 ## Highlights
- All linters passed ✔️
- Home and About pages 👍🏼 
- Updated Readme ✔️

 ## Required Changes ♻️
_Check the comments under the review._
- [x] As the previous reviewer pointed out, the video presentation is still missing the aspect that interests you. I will encourage you to specifically state that 'this this this' are the areas that interest me.
- [x] The changes you made are not reflected on your published pages, kindly ensure all changes are published accordingly so that they won't only be in your GitHub account but also seen live.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-25 06:12 UTC, christianbiring1 requested changes
Hi @developertariq , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
# STATUS: REQUEST CHANGES :recycle: 
![soclose](https://user-images.githubusercontent.com/97100091/203912661-697fe8e7-4c12-45e4-85eb-6da381a229ba.gif)



 ## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] Desscriptive PR `title` and `summary`

 ## Required Changes ♻️
- [ ] `KINDLY MAKE SURE YOU IMPLEMENT ALL THE CHANGES REQUESTED BY THE PREVIOUS REVIEWER BEFORE YOU RESUBMIT FOR ANOTHER REVIEW`
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-25 06:12 UTC, christianbiring1 commented on css/about.css
> +  font-size: 0.875em;
- [ ] As said previously, Kindly make sure you implement the suggested changes by the previous reviewers.You need to stick to the origin design `(typos, font, spacing, and color)`

What was said previously :point_down: 
![image](https://user-images.githubusercontent.com/97100091/203912141-be78e658-b69d-4392-9257-3ce20e01b4ad.png)

2022-11-25 07:49 UTC, omarsalem7 approved these changes
Hi @developertariq 😊, 
# STATUS: APPROVED! 🥇 💯 

![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-25 07:56 UTC, merged